### ISSUE TITLE
Return after reject

### ISSUE THREAD

**Issue by vladblindu** [oychao/promise-jsonfile#12]
Hello and thank you.
I think I found a bug 
[here](https://github.com/oychao/promise-jsonfile/blob/84f2b815b0a894c078f643192c5b9e569520c2fd/index.js#L24) thats very easy to fix.
After rejecting execution should stop. Otherwise it will try to stripBOM from an undefined buffer and therefore crash.
I could easily be fix it by wrapping the rest of the function in an else clause or inserting a return after the reject clause.

**Comment by oychao** [comment]
Hi @vladblindu , bug fixed now and a new version has been published to NPM, thank you for your feedback.
