### ISSUE TITLE
Small console.log fix

### ISSUE THREAD

**Issue by vladblindu** [oychao/promise-jsonfile#14]
[Here](https://github.com/oychao/promise-jsonfile/blob/bc78a277d44817aec019027b3f37b1184b33b2f7/index.js#L24) the console.log should be moved inside the **if** clause and maybe replaced with a console.error. It logs an unwanted "null". 
I was searching through my own code to discover the leaking console.log and found it in your package.
It's nothing dramatical, but it helps guys like me, that forget were they put logs in their own code :)
Thanks a lot for your time.

**Comment by oychao** [comment]
My mistake, I forgot to remove the console line, I republished a new version(v1.0.3), thank you very much.

**Comment by oychao** [comment]
@mcmunder   
I republished a new version(v1.0.4), I forgot to build before publishing v1.0.3.  
Sorry.
